name: CI Java (Host)

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"
  workflow_dispatch:

jobs:
  build:
    name: build-sonar-site-upload
    uses: ebpro/gh-actions-shared-java/.github/workflows/ci-shareable-maven.yml@develop
    secrets: inherit
    with:
      runs-on: ebpro-org
      quality-goal-run: "true"
      deploy-goal-run: "true"
      site-goal-run: "true"
      site-goal-branch: "master"